version: '3'

services:
  app:
    container_name: recipe_app
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: ["sh", "-c", "python manage.py runserver 0.0.0.0:8000"]